import { claimed } from "../helpers";
import type { Text } from "../types";

export const ui = {
  cta: {
    trial: "Essayer 14 jours gratuitement",
    trialShort: "Essai gratuit",
    demo: "Réserver une démo",
    expert: "Parler à un expert",
    signupEquipe: "Réserver une démo",
    signupAgence: "Réserver une démo",
    login: "Connexion",
    comparePlans: "Comparer les formules",
    learnMore: "En savoir plus",
  },
  microcopy: {
    trial: ["Sans carte bancaire", claimed("Hébergé en France", "hosting-fr", "Support en français"), "Sans engagement"] as Text[],
  },
  badges: {
    soon: "Bientôt",
    recommended: "Recommandé",
    annualDiscount: "−20 %",
    new: "Nouveau",
  },
  header: {
    skip: "Aller au contenu",
    home: "Suzalink, accueil",
    features: "Fonctionnalités",
    featuresAll: "Toutes les fonctionnalités",
    featuresAllBlurb: "Les sept modules, inclus dans chaque formule.",
    integrations: "Intégrations",
    solutions: "Solutions",
    pricing: "Tarifs",
    surMesure: "Sur-mesure",
    resources: "Ressources",
    resourcesItems: [
      { label: "Nouveautés", blurb: "Ce qui vient de sortir et ce qui arrive.", href: "/nouveautes" },
      { label: "Intégrations", blurb: "Les outils branchés sur Suzalink.", href: "/integrations" },
      { label: "Sécurité et RGPD", blurb: "Hébergement, sauvegardes, sous-traitants.", href: "/securite" },
      { label: "À propos", blurb: "Construit par des agences de prospection.", href: "/a-propos" },
    ],
    resourcesSoon: "Blog et guides",
    menu: "Menu",
    closeMenu: "Fermer le menu",
  },
  footer: {
    pitch: "La console d'exécution commerciale : appels, emails, listes et rendez-vous au même endroit.",
    modules: "Modules",
    solutions: "Solutions",
    company: "Entreprise",
    legal: "Légal",
    companyLinks: [
      { label: "Tarifs", href: "/tarifs" },
      { label: "Sur-mesure", href: "/sur-mesure" },
      { label: "À propos", href: "/a-propos" },
      { label: "Nouveautés", href: "/nouveautes" },
      { label: "Intégrations", href: "/integrations" },
      { label: "Sécurité et RGPD", href: "/securite" },
      { label: "Réserver une démo", href: "/demo" },
    ],
    legalLinks: [
      { label: "Mentions légales", href: "/mentions-legales" },
      { label: "CGV", href: "/cgv" },
      { label: "Confidentialité", href: "/confidentialite" },
      { label: "Cookies", href: "/cookies" },
      { label: "DPA", href: "/dpa" },
    ],
    cookieSettings: "Gérer les cookies",
    status: "Statut du service",
    linkedin: "LinkedIn",
    hosted: claimed("Hébergé en France", "hosting-fr", "Conçu en France") as Text,
    rights: "© 2026 Suzalink. Tous droits réservés.",
  },
  mobileBar: {
    label: "Démarrer avec Suzalink",
  },
  consent: {
    title: "Vos cookies, votre choix",
    body: "Nous utilisons des cookies de mesure d'audience et, si vous l'acceptez, de publicité (LinkedIn). Rien n'est déposé avant votre choix. Vous pouvez le modifier à tout moment en bas de page.",
    accept: "Accepter",
    refuse: "Refuser",
    customize: "Personnaliser",
    save: "Enregistrer mes choix",
    policy: "Politique cookies",
    categories: {
      necessary: { title: "Nécessaires", body: "Mémoriser votre choix de cookies et sécuriser les formulaires. Toujours actifs." },
      analytics: { title: "Mesure d'audience", body: "Comprendre quelles pages aident nos visiteurs (PostHog, hébergé dans l'UE)." },
      marketing: { title: "Publicité", body: "Mesurer nos campagnes LinkedIn. Désactivé tant que vous ne l'acceptez pas." },
    },
  },
  forms: {
    required: "obligatoire",
    choose: "Sélectionnez",
    optional: "facultatif",
    submit: "Continuer",
    sending: "Envoi en cours…",
    personalEmail: "Cette adresse semble personnelle. Une adresse professionnelle nous aide à préparer la démo, mais vous pouvez continuer.",
    errors: {
      generic: "L'envoi n'a pas abouti. Réessayez dans un instant ou écrivez-nous à contact@suzalink.com.",
      rateLimited: "Trop de tentatives. Patientez une minute avant de réessayer.",
      captcha: "La vérification anti-spam a échoué. Rechargez la page puis réessayez.",
      email: "Indiquez une adresse email valide.",
      required: "Ce champ est obligatoire.",
      phone: "Indiquez un numéro de téléphone valide.",
    },
    consent: "En envoyant ce formulaire, vous acceptez que Suzalink traite ces informations pour vous recontacter, conformément à notre politique de confidentialité.",
    teamSizes: [
      { value: "1", label: "Juste moi" },
      { value: "2-5", label: "2 à 5" },
      { value: "6-10", label: "6 à 10" },
      { value: "11+", label: "11 et plus" },
    ],
  },
  cal: {
    loading: "Chargement des créneaux…",
    missing: "La prise de rendez-vous en ligne arrive. En attendant, nous vous rappelons sous un jour ouvré pour fixer le créneau.",
    timezone: "Créneaux de 30 minutes, heure de Paris, du lundi au vendredi.",
  },
  placeholders: {
    screenshot: "Capture à venir",
    visual: "Visuel à venir",
    photo: "Photo à venir",
  },
  breadcrumbs: { home: "Accueil", features: "Fonctionnalités", solutions: "Solutions" },
  module: {
    highlights: "Ce que vous pouvez faire",
    addon: "En option",
    addonLink: "Voir les options sur la page Tarifs",
    soon: "Bientôt sur ce module",
    related: "Les autres modules",
    faq: "Questions fréquentes",
    included: "Inclus dans Solo, Équipe et Agence",
  },
  solution: {
    pains: "Ce qui vous freine aujourd'hui",
    features: "Ce que Suzalink change",
    plan: "La formule faite pour vous",
    seePricing: "Voir tous les tarifs",
    faq: "Questions fréquentes",
    finalTrial: "Récupérez vos heures dès aujourd'hui.",
    finalDemo: "Voyons votre cas ensemble.",
    finalSub: "30 minutes avec un expert, puis {{trial.days}} jours pour tout essayer.",
    finalSubTrial: "{{trial.days}} jours pour essayer, sans carte bancaire.",
  },
  notFound: {
    title: "Cette page a raccroché.",
    body: "Le lien est peut-être ancien, ou la page a changé d'adresse. Repartons d'un endroit connu.",
    home: "Retour à l'accueil",
    pricing: "Voir les tarifs",
  },
};

export type Ui = typeof ui;
