// Generated by scripts/build-europe-map.ts from Natural Earth (world-atlas 50m). Do not edit.
// Country shapes live in public/visuals/v9-europe-map.svg.
export const MAP_WIDTH = 640;
export const MAP_HEIGHT = 560;
export const MAP_SRC = "/visuals/v9-europe-map.svg";
export const NODES = {"FR":[288.4,288.3],"DE":[433.8,157.3],"ES":[153.1,464.9]} as const;
