// Generates the V9 hosting map (France + backups in Germany and Spain) from
// Natural Earth data, so country shapes are exact rather than drawn by hand.
// Run with: npm run build:map (writes src/components/visuals/europe-map-data.ts)
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoAzimuthalEqualArea, geoCentroid, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import type { Feature, FeatureCollection, Geometry } from "geojson";
import type { Topology } from "topojson-specification";

const require = createRequire(import.meta.url);
const world = require("world-atlas/countries-50m.json") as Topology;

const WIDTH = 640;
const HEIGHT = 560;
const FOCUS = { FR: "250", DE: "276", ES: "724" } as const;

const countries = feature(world, world.objects.countries) as FeatureCollection<Geometry, { name: string }>;

// Frame the map on metropolitan France, Spain, Germany and their neighbours.
const projection = geoAzimuthalEqualArea()
  .rotate([-4, -47])
  .scale(1650)
  .translate([WIDTH / 2, HEIGHT / 2])
  .clipExtent([
    [0, 0],
    [WIDTH, HEIGHT],
  ]);

const path = geoPath(projection).digits(0);

const shapes: { id: string; name: string; d: string }[] = [];
for (const f of countries.features as Feature<Geometry, { name: string }>[]) {
  const d = path(f);
  if (!d) continue;
  const [[x0, y0], [x1, y1]] = path.bounds(f);
  if (x1 < 0 || y1 < 0 || x0 > WIDTH || y0 > HEIGHT) continue;
  shapes.push({ id: String(f.id), name: f.properties.name, d });
}

// Metropolitan centroids (France's own centroid is pulled off by overseas territories).
const anchors: Record<keyof typeof FOCUS, [number, number]> = {
  FR: [2.4, 46.7],
  DE: [10.3, 51.1],
  ES: [-3.6, 40.3],
};
const nodes = Object.fromEntries(
  Object.entries(anchors).map(([k, lonLat]) => {
    const [x, y] = projection(lonLat)!;
    return [k, [Math.round(x * 10) / 10, Math.round(y * 10) / 10]];
  }),
);

// Sanity check: Spain's centroid should project inside the frame.
const es = countries.features.find((f) => String(f.id) === FOCUS.ES)!;
const esC = projection(geoCentroid(es))!;
if (esC[0] < 0 || esC[1] > HEIGHT) throw new Error("Spain is outside the frame");

// Country shapes go to a static, cacheable SVG; only the nodes stay in the page.
const fill = (id: string) =>
  id === FOCUS.FR ? "#DFE4FF" : id === FOCUS.DE || id === FOCUS.ES ? "#EFF1FF" : "#ECEEF2";
const stroke = (id: string) => (id === FOCUS.FR ? "#3355FF" : "#FFFFFF");
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${HEIGHT}" width="${WIDTH}" height="${HEIGHT}">
<defs><radialGradient id="f" cx="50%" cy="50%" r="62%"><stop offset="70%" stop-color="#fff"/><stop offset="100%" stop-color="#000"/></radialGradient>
<mask id="m"><rect width="${WIDTH}" height="${HEIGHT}" fill="url(#f)"/></mask></defs>
<g mask="url(#m)" stroke-linejoin="round">
${shapes
  .map((s) => `<path d="${s.d}" fill="${fill(s.id)}" stroke="${stroke(s.id)}" stroke-width="${s.id === FOCUS.FR ? 1.5 : 1}"/>`)
  .join("")}
</g></svg>
`;
writeFileSync(new URL("../public/visuals/v9-europe-map.svg", import.meta.url), svg);

const out = `// Generated by scripts/build-europe-map.ts from Natural Earth (world-atlas 50m). Do not edit.
// Country shapes live in public/visuals/v9-europe-map.svg.
export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};
export const MAP_SRC = "/visuals/v9-europe-map.svg";
export const NODES = ${JSON.stringify(nodes)} as const;
`;

writeFileSync(new URL("../src/components/visuals/europe-map-data.ts", import.meta.url), out);
console.log(`Wrote ${shapes.length} countries: ${(svg.length / 1024).toFixed(1)} KB SVG`);
